"""empty message

Revision ID: b345a5bdfc40
Revises: 
Create Date: 2017-11-27 21:35:58.038226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b345a5bdfc40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alarm_level_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warning', sa.SmallInteger(), nullable=True),
    sa.Column('error', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grain_storehouse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storehouse_no', sa.String(length=10), nullable=False),
    sa.Column('storehouse_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storehouse_no')
    )
    op.create_table('node_mqtt_trans_func',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gateway_addr', sa.String(length=3), nullable=True),
    sa.Column('node_addr', sa.String(length=13), nullable=True),
    sa.Column('trans_direct', sa.String(length=1), nullable=True),
    sa.Column('func_code', sa.String(length=7), nullable=True),
    sa.Column('wind_direct', sa.String(length=2), nullable=True),
    sa.Column('wind_speed', sa.String(length=2), nullable=True),
    sa.Column('model', sa.String(length=10), nullable=True),
    sa.Column('on_off', sa.String(length=2), nullable=True),
    sa.Column('work_mode', sa.String(length=3), nullable=True),
    sa.Column('temp', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('power_io',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('addr', sa.String(length=8), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('addr')
    )
    op.create_table('power_io_rs485_func',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('function_name', sa.String(length=50), nullable=True),
    sa.Column('function_code', sa.SmallInteger(), nullable=True),
    sa.Column('start_at_reg_high', sa.SmallInteger(), nullable=True),
    sa.Column('start_at_reg_low', sa.SmallInteger(), nullable=True),
    sa.Column('num_of_reg_high', sa.SmallInteger(), nullable=True),
    sa.Column('num_of_reg_low', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('function_name')
    )
    op.create_table('tianshuo_rs485',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('addr', sa.String(length=8), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('addr')
    )
    op.create_table('tianshuo_rs485_func',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('function_name', sa.String(length=50), nullable=True),
    sa.Column('function_code', sa.SmallInteger(), nullable=True),
    sa.Column('start_at_reg_high', sa.SmallInteger(), nullable=True),
    sa.Column('start_at_reg_low', sa.SmallInteger(), nullable=True),
    sa.Column('num_of_reg_high', sa.SmallInteger(), nullable=True),
    sa.Column('num_of_reg_low', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('function_name')
    )
    op.create_table('lora_gateway',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gateway_addr', sa.String(length=4), nullable=False),
    sa.Column('grain_storehouse_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grain_storehouse_id'], ['grain_storehouse.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gateway_addr')
    )
    op.create_table('grain_barn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barn_no', sa.String(length=10), nullable=True),
    sa.Column('barn_name', sa.String(length=50), nullable=True),
    sa.Column('grain_storehouse_id', sa.Integer(), nullable=False),
    sa.Column('lora_gateway_id', sa.Integer(), nullable=False),
    sa.Column('high_limit', sa.Float(), nullable=True),
    sa.Column('low_limit', sa.Float(), nullable=True),
    sa.Column('current_limit', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['grain_storehouse_id'], ['grain_storehouse.id'], ),
    sa.ForeignKeyConstraint(['lora_gateway_id'], ['lora_gateway.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barn_no')
    )
    op.create_table('lora_node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_addr', sa.String(length=8), nullable=True),
    sa.Column('grain_storehouse_id', sa.Integer(), nullable=False),
    sa.Column('lora_gateway_id', sa.Integer(), nullable=False),
    sa.Column('grain_barn_id', sa.Integer(), nullable=False),
    sa.Column('power_io_id', sa.Integer(), nullable=False),
    sa.Column('current', sa.Float(), nullable=True),
    sa.Column('auto_manual', sa.String(length=8), nullable=True),
    sa.Column('manual_start_time', sa.DateTime(), nullable=True),
    sa.Column('manual_end_time', sa.DateTime(), nullable=True),
    sa.Column('auto_start_time', sa.DateTime(), nullable=True),
    sa.Column('auto_end_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['grain_barn_id'], ['grain_barn.id'], ),
    sa.ForeignKeyConstraint(['grain_storehouse_id'], ['grain_storehouse.id'], ),
    sa.ForeignKeyConstraint(['lora_gateway_id'], ['lora_gateway.id'], ),
    sa.ForeignKeyConstraint(['power_io_id'], ['power_io.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_addr')
    )
    op.create_table('grain_temp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grain_storehouse_id', sa.Integer(), nullable=False),
    sa.Column('lora_gateway_id', sa.Integer(), nullable=False),
    sa.Column('grain_barn_id', sa.Integer(), nullable=False),
    sa.Column('lora_node_id', sa.Integer(), nullable=False),
    sa.Column('switch', sa.Boolean(), nullable=True),
    sa.Column('temp1', sa.Float(), nullable=True),
    sa.Column('temp2', sa.Float(), nullable=True),
    sa.Column('temp3', sa.Float(), nullable=True),
    sa.Column('battery_vol', sa.SmallInteger(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['grain_barn_id'], ['grain_barn.id'], ),
    sa.ForeignKeyConstraint(['grain_storehouse_id'], ['grain_storehouse.id'], ),
    sa.ForeignKeyConstraint(['lora_gateway_id'], ['lora_gateway.id'], ),
    sa.ForeignKeyConstraint(['lora_node_id'], ['lora_node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grain_temp')
    op.drop_table('lora_node')
    op.drop_table('grain_barn')
    op.drop_table('lora_gateway')
    op.drop_table('tianshuo_rs485_func')
    op.drop_table('tianshuo_rs485')
    op.drop_table('power_io_rs485_func')
    op.drop_table('power_io')
    op.drop_table('node_mqtt_trans_func')
    op.drop_table('grain_storehouse')
    op.drop_table('alarm_level_setting')
    # ### end Alembic commands ###
